### ISSUE TITLE
Create Mock-Up For Register Screen

### ISSUE THREAD

**Issue by henrysdev** [josselaer/gmpt#10]
Non-functional GUI layout for register screen.

**Comment by henrysdev** [comment]
Non-functional GUI layout for register screen.

**Comment by Lorsen** [comment]
Username Label & text input field
First Name Label & text input field
Last Name Label & text input field
Password label & text input field (2-30 characters - placeholder too)
Confirm password label and text input field
E-mail label and input field 
Add functionality to check for valid e-mail
Submit Button
